kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine
  envoriment:
     - FOO=bar
     - MY_SECRET=${MY_SECRET}
  commands:
    - echo $FOO
    - echo $MY_SECRET
    - echo "${MY_SECRET}"
    
- name: docker  
  image: plugins/docker
  settings:
    repo: danielhauge/metis-showcase
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password