kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine
  secrets: [docker_password, DOCKER_USERNAME]
  environment:
    USERNAME:
      from_secret: docker_username
  commands:
    - echo $docker_username
    - echo "${docker_username}"
    - echo "${DOCKER_USERNAME}"
    - echo ${DOCKER_USERNAME}


- name: docker  
  image: plugins/docker
  settings:
    repo: danielhauge/metis-showcase
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password