kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build  
    image: plugins/docker
    settings:
      registry: docker.io
      repo: danielhauge/metis-showcase
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: feveile-hauge.com
      username: root
      key:
        from_secret: metis_key
      port: 22
      script:
      - docker pull danielhauge/metis-showcase:latest
      - docker service update --image danielhauge/metis-showcase:latest showcase