kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: danielhauge/metis-showcase
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password