kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

- name: docker
  image: plugins/docker
  settings:
    registry: registry.hub.docker.com
    repo: danielhauge/metis-showcase
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password